apiVersion: v1
kind: Service
metadata:
  name: backend-app
spec:
  selector:
    app: backend-app
  ports:
    - protocol: TCP
      name: backend
      port: 8081
      targetPort: 8081
    - protocol: TCP
      name: frontend
      port: 3001
      targetPort: 3000
  type: LoadBalancer
